---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Bodyweight Tracking API"
paths:
  /authorize:
    post:
      x-swagger-router-controller: "index"
      operationId: "authorizePOST"
      description: "Authorize the user to access data."
      tags:
      - "Security"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/LoginPostRequestBody"
      responses:
        200:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/User"
          headers:
            access-token:
              type: "string"
              description: "Access token."
        400:
          description: "Bad request."
        401:
          description: "Unauthorized."
        500:
          description: "Server error."
  /measurements:
    get:
      x-swagger-router-controller: "index"
      operationId: "measurementsGET"
      description: "Get bodyweight measurements."
      tags:
      - "Measurements"
      produces:
      - "application/json"
      parameters:
      - name: "access-token"
        in: "header"
        description: "Access token."
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Measurement"
        401:
          description: "Unauthorized."
        500:
          description: "Server error."
    post:
      x-swagger-router-controller: "index"
      operationId: "measurementsPOST"
      description: "Store a new measurement."
      tags:
      - "Measurements"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "access-token"
        in: "header"
        description: "Access token."
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/MeasurementPostRequestBody"
      responses:
        201:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/Measurement"
        400:
          description: "Bad request."
        401:
          description: "Unauthorized."
        500:
          description: "Server error."
  /measurements/{measurementId}:
    delete:
      x-swagger-router-controller: "index"
      operationId: "measurementDELETE"
      description: "Delete the measurement associated to the specified ID."
      tags:
      - "Measurements"
      parameters:
      - name: "measurementId"
        in: "path"
        required: true
        type: "integer"
      - name: "access-token"
        in: "header"
        description: "Access token."
        required: true
        type: "string"
      responses:
        204:
          description: "Successful operation."
        401:
          description: "Unauthorized."
        404:
          description: "Not found."
        500:
          description: "Server error."
    patch:
      x-swagger-router-controller: "index"
      operationId: "measurementPATCH"
      description: "Edit the measurement associated to the specified ID."
      tags:
      - "Measurements"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "measurementId"
        in: "path"
        required: true
        type: "integer"
      - name: "access-token"
        in: "header"
        description: "Access token."
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/MeasurementPatchRequestBody"
      responses:
        200:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/Measurement"
        400:
          description: "Bad request."
        401:
          description: "Unauthorized."
        404:
          description: "Not found."
        500:
          description: "Server error."
definitions:
  LoginPostRequestBody:
    type: "object"
    required:
    - "password"
    - "username"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  Measurement:
    type: "object"
    required:
    - "date"
    - "id"
    - "unit"
    - "value"
    properties:
      id:
        type: "number"
      value:
        type: "number"
      unit:
        type: "string"
      date:
        type: "string"
  MeasurementPostRequestBody:
    type: "object"
    required:
    - "date"
    - "unit"
    - "value"
    properties:
      value:
        type: "number"
      unit:
        type: "string"
      date:
        type: "string"
  MeasurementPatchRequestBody:
    type: "object"
    properties:
      value:
        type: "number"
      unit:
        type: "string"
      date:
        type: "string"
  User:
    type: "object"
    properties:
      username:
        type: "string"
      avatarUrl:
        type: "string"
